server:
  port: 9000
spring:
  application:
    name: Eureka Server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true